### ISSUE TITLE
Unwrapping of main functionality from `run` functions

### ISSUE THREAD

**Issue by emanjavacas** [emanjavacas/pie#27]
Hi @PonteIneptique, I was wondering if there was a compelling reason to wrap all main blocks inside a `run` function (e.g. `pie/scripts/evaluate.py`)? I would prefer to unwrap them if it's ok, since that allows me to easily inspect the instantiated objects in the script (using `python -i`).

**Comment by PonteIneptique** [comment]
Well, I think so.

1. This is what ends up being up at the CLI level : https://github.com/emanjavacas/pie/blob/master/pie/scripts/group.py . The if __main__ should actually disappear now that I think about it.
2. Having a cli registered function (using decorators) and a separate run function is good design because it allows to test it separately (I have had really bad time setting up test for comands and this design ends up being the easiest to deal with ultimately)
3. A benefit but not technically the objective, this provides a simple to use API for users if they want to call that from within python.

Note that if you need to get access to some items inside, could we simply move some to Classes with `__call__()` and give access to some states ?

**Comment by emanjavacas** [comment]
Right. I had forgotten about the CLI. :-)
Nevermind. I feel changing anything now in the suggested direction would make everything more difficult to maintain. I will just look for an alternative solution!
